Carilah Gradient dari sebuah fungsi berikut : 3𝑥+4𝑦=5

In [1]:
import sympy as sy
import numpy as np
import numdifftools as nd

In [2]:
from sympy.abc import x,y

In [3]:
fx= (5-3*x)/4
fy= (5-4*y)/3
print(fx,fy)

5/4 - 3*x/4 5/3 - 4*y/3


In [4]:
sy.tensor.array.derive_by_array(fx,(x,y))

[-3/4, 0]

In [5]:
sy.tensor.array.derive_by_array(fy,(x,y))

[0, -4/3]

In [6]:
sy.tensor.array.derive_by_array((3*x+4*y-5),(x,y))

[3, 4]

In [7]:
dx = 0.5 #step
x = np.arange(0,1,dx)
y = 1 # anggap sebagai konstanta
fx = (5-3*x)/4
dfdx = np.gradient(fx,dx)
dfdx

array([-0.75, -0.75])

In [8]:
dy = 0.5 #step
y = np.arange(0,1,dx)
x = 1 # anggap sebagai konstanta
fy = (5-4*y)/3
dfdy = np.gradient(fy,dy)
dfdy

array([-1.33333333, -1.33333333])

In [9]:
dx=dy = 0.5 
x = np.arange(0,1,dx)
y = np.arange(0,1,dy)
fx = x*3 -5 +4*y
dfdx = np.gradient(fx,dx)
dfdy = np.gradient(fx,dy)

print(x)
print(y)
print(fx)
print(dfdx)
print(dfdy)

[0.  0.5]
[0.  0.5]
[-5.  -1.5]
[7. 7.]
[7. 7.]


In [10]:
f = lambda x: (5-3*x)/4
grad1 = nd.Gradient(f)([1])
print("Gradient of x * 3 + y*4 - 5 at x = 1 is ", grad1)

Gradient of x * 3 + y*4 - 5 at x = 1 is  -0.7499999999999998


In [11]:
f = lambda y:(5-4*y)/3
grad1 = nd.Gradient(f)([1])
print("Gradient of x * 3 + y*4 - 5 at y = 1 is ", grad1)

Gradient of x * 3 + y*4 - 5 at y = 1 is  -1.3333333333333326


In [14]:
y=(5-3*x)/4

In [15]:
f=3*x+4*y-5

In [16]:
f

0

In [17]:
x=np.linspace(0,10,11)
x

array([ 0., 10.])

In [18]:
y=(5-3*x)/4
y

array([ 1.25, -6.25])

In [19]:
np.gradient(y,x)

array([-0.75, -0.75])

In [20]:
y=np.linspace(0,10,11)
y

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.gradient(x)

array([-1.33333333, -1.33333333, -1.33333333, -1.33333333, -1.33333333,
       -1.33333333, -1.33333333, -1.33333333, -1.33333333, -1.33333333,
       -1.33333333])