- Buatlah Tensor di bawah ini dengan Python:[[23 50 7 12] [57 67 99 43] [75 21 57 12] [87 26 18 84]]
- Lakukan perkalian terhadap matrix berikut: 𝐴= [23 50 19 7 12 109 57 67 98] 98,𝐵= [17 22 19]
- Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini: 𝐴= [23 50 19 7 12 109 57 67 98]

In [1]:
import numpy as np

In [3]:
Tensor=np.array([[[23,50],[7,12]],
[[55,67],[99,43]],
[[75,21],[57,12]],
[[87,26],[18,84]]])
Tensor

array([[[23, 50],
        [ 7, 12]],

       [[55, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [14]:
A=np.array([[23 ,50 ,19] ,
[7 ,12 ,109] ,
[57 ,67 ,98]])
print(A)
𝐵= np.array([17, 22 ,19])
print(B)
print(A@B)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[17 22 19]
[1852 2454 4305]


In [17]:
print(A.T)
print(np.linalg.det(A))
print(np.linalg.inv(A))

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]
131344.0000000002
[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
