1. Buatlah vektor di bawah ini dengan Python:(17 22 19)
2. Diberikan3 buahvector 3 dimensi:𝑨=(17 22 19),𝑩=(10 20 11),𝑪=(5 12 9)
3. Hitunglah:
- A+B
- B-C
- A dot C
- A x B
- norm A
- Sudut antara vektor A dan B

In [2]:
import numpy as np

In [5]:
A=np.array([17,22,19])
B=np.array([10,20,11])
C=np.array([5,12,9])

In [27]:
def cos_theta(A,B):
    return(A@B/(np.linalg.norm(A)*np.linalg.norm(B)))


In [28]:
print(A+B)
print(B-C)
print(A@C)
print(A*B)
print(np.linalg.norm(A))
print(cos_theta(A,B))

[27 42 30]
[5 8 2]
520
[170 440 209]
33.67491648096547
0.9759590023331435
